from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from jinja2 import Environment, FileSystemLoader, StrictUndefined

from . import ROOT

TEMPLATES = ROOT / "templates"
MARKER = "GENERATED BY SINAN"
HTML_START = "<!-- GENERATED BY SINAN: {name} v1 START -->"
HTML_END = "<!-- GENERATED BY SINAN: {name} v1 END -->"
YAML_START = "# GENERATED BY SINAN: {name} v1 START"
YAML_END = "# GENERATED BY SINAN: {name} v1 END"


def env() -> Environment:
    return Environment(
        loader=FileSystemLoader(str(TEMPLATES)),
        undefined=StrictUndefined,
        autoescape=False,
        keep_trailing_newline=True,
        lstrip_blocks=True,
        trim_blocks=True,
    )


def render_template(template: str, context: dict[str, Any]) -> str:
    return env().get_template(template).render(**context).strip() + "\n"


def marker_pair(relative_path: str, name: str) -> tuple[str, str]:
    if relative_path.endswith((".yml", ".yaml")):
        return YAML_START.format(name=name), YAML_END.format(name=name)
    return HTML_START.format(name=name), HTML_END.format(name=name)


def mark_content(relative_path: str, name: str, body: str) -> str:
    start, end = marker_pair(relative_path, name)
    return f"{start}\n{body.strip()}\n{end}\n"


def has_marker(source: str | None) -> bool:
    if not source:
        return False
    start = re.search(r"(?m)^(?:<!-- |# )GENERATED BY SINAN: .+ v1 START(?: -->)?$", source)
    end = re.search(r"(?m)^(?:<!-- |# )GENERATED BY SINAN: .+ v1 END(?: -->)?$", source)
    return bool(start and end)


def replace_marked(existing: str, desired: str) -> str:
    start = desired.splitlines()[0]
    end = desired.rstrip().splitlines()[-1]
    if start not in existing or end not in existing:
        return existing
    prefix, rest = existing.split(start, 1)
    _, suffix = rest.split(end, 1)
    return f"{prefix}{desired.rstrip()}{suffix}"


def read_text(path: Path) -> str | None:
    if not path.exists():
        return None
    return path.read_text(encoding="utf8")


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf8")
