#!/usr/bin/env node
"use strict";

const fs = require("node:fs");
const path = require("node:path");

const GLOSSARY_MARKER_START = "<!-- GENERATED BY SINAN: captured-terms v1 START -->";
const GLOSSARY_MARKER_END = "<!-- GENERATED BY SINAN: captured-terms v1 END -->";

function parseArgs(argv) {
  const args = {
    target: process.cwd(),
    terms: [],
    decisions: [],
    adrTitle: null,
    adrDecision: null,
    adrContext: "Captured from confirmed project discussion.",
    adrConsequences: [],
    status: "accepted",
    date: new Date().toISOString().slice(0, 10),
    write: false,
    check: false,
    json: false,
  };

  for (let index = 2; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === "--target") args.target = argv[++index];
    else if (arg === "--term") args.terms.push(parsePair(argv[++index], "--term"));
    else if (arg === "--decision") args.decisions.push(parsePair(argv[++index], "--decision"));
    else if (arg === "--adr-title") args.adrTitle = argv[++index];
    else if (arg === "--adr-decision") args.adrDecision = argv[++index];
    else if (arg === "--adr-context") args.adrContext = argv[++index];
    else if (arg === "--adr-consequence") args.adrConsequences.push(argv[++index]);
    else if (arg === "--status") args.status = argv[++index];
    else if (arg === "--date") args.date = argv[++index];
    else if (arg === "--write") args.write = true;
    else if (arg === "--check") args.check = true;
    else if (arg === "--json") args.json = true;
    else if (arg === "--help") {
      printHelp();
      process.exit(0);
    } else {
      throw new Error(`unknown argument: ${arg}`);
    }
  }

  if (args.adrTitle || args.adrDecision) {
    if (!args.adrTitle || !args.adrDecision) {
      throw new Error("--adr-title and --adr-decision must be provided together");
    }
    args.decisions.push({
      name: args.adrTitle,
      value: args.adrDecision,
    });
  }
  return args;
}

function printHelp() {
  console.log(`Usage: node scripts/decision-capture.js [options]

Dry-run by default. Use --write to update GLOSSARY.md and docs/adr/.

Examples:
  node scripts/decision-capture.js --term "Workflow=Repeatable sequence with gates"
  node scripts/decision-capture.js --adr-title "Use Postgres" --adr-decision "Use Postgres for durable state" --write
`);
}

function parsePair(value, flag) {
  if (!value) throw new Error(`${flag} requires NAME=TEXT`);
  const separator = value.includes("=") ? "=" : value.includes(":") ? ":" : null;
  if (!separator) throw new Error(`${flag} requires NAME=TEXT`);
  const [name, ...rest] = value.split(separator);
  const trimmedName = name.trim();
  const trimmedValue = rest.join(separator).trim();
  if (!trimmedName || !trimmedValue) throw new Error(`${flag} requires non-empty NAME and TEXT`);
  return { name: trimmedName, value: trimmedValue };
}

function readIfExists(filePath) {
  return fs.existsSync(filePath) ? fs.readFileSync(filePath, "utf8") : "";
}

function slugify(value) {
  return String(value)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 72) || "decision";
}

function extractGeneratedBlock(existing) {
  const start = existing.indexOf(GLOSSARY_MARKER_START);
  const end = existing.indexOf(GLOSSARY_MARKER_END);
  if (start === -1 || end === -1 || end <= start) return null;
  return existing.slice(start + GLOSSARY_MARKER_START.length, end);
}

function parseExistingTerms(existing) {
  const block = extractGeneratedBlock(existing);
  if (!block) return new Map();
  const terms = new Map();
  for (const line of block.split("\n")) {
    const match = line.match(/^- \*\*(.+?)\*\*: (.+)$/);
    if (match) terms.set(match[1], match[2]);
  }
  return terms;
}

function glossaryBlock(terms) {
  const lines = [...terms.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([name, value]) => `- **${name}**: ${value}`);
  return `${GLOSSARY_MARKER_START}\n## Captured Terms\n\n${lines.join("\n")}\n${GLOSSARY_MARKER_END}\n`;
}

function upsertGlossary(existing, incomingTerms) {
  const terms = parseExistingTerms(existing);
  for (const term of incomingTerms) terms.set(term.name, term.value);
  if (terms.size === 0) return existing;

  const base = existing.trim() ? existing : "# Glossary\n";
  const start = base.indexOf(GLOSSARY_MARKER_START);
  const end = base.indexOf(GLOSSARY_MARKER_END);
  const generated = glossaryBlock(terms);
  if (start !== -1 && end !== -1 && end > start) {
    return `${base.slice(0, start)}${generated.trimEnd()}${base.slice(end + GLOSSARY_MARKER_END.length)}`
      .replace(/\n{3,}/g, "\n\n")
      .trimEnd() + "\n";
  }
  return `${base.trimEnd()}\n\n${generated}`;
}

function formatAdr(decision, options) {
  const consequences = options.adrConsequences.length > 0 ? options.adrConsequences : ["Review this decision when constraints change."];
  return `# ${decision.name}

Status: ${options.status}
Date: ${options.date}

## Context

${options.adrContext}

## Decision

${decision.value}

## Consequences

${consequences.map((item) => `- ${item}`).join("\n")}

## Validation

- Link this ADR from related issues, PRs, or implementation plans.
- Revisit if the first implementation slice contradicts the stated constraints.
`;
}

function desiredWrites(options) {
  const target = path.resolve(options.target || process.cwd());
  if (!fs.existsSync(target) || !fs.statSync(target).isDirectory()) {
    throw new Error(`target must be a directory: ${target}`);
  }

  const writes = [];
  if (options.terms.length > 0) {
    const glossaryPath = path.join(target, "GLOSSARY.md");
    writes.push({
      path: glossaryPath,
      content: upsertGlossary(readIfExists(glossaryPath), options.terms),
      kind: "glossary",
    });
  }

  for (const decision of options.decisions) {
    const adrPath = path.join(target, "docs", "adr", `${options.date}-${slugify(decision.name)}.md`);
    writes.push({
      path: adrPath,
      content: formatAdr(decision, options),
      kind: "adr",
    });
  }

  return { target, writes };
}

function run(options = {}) {
  const normalized = {
    target: process.cwd(),
    terms: [],
    decisions: [],
    adrContext: "Captured from confirmed project discussion.",
    adrConsequences: [],
    status: "accepted",
    date: new Date().toISOString().slice(0, 10),
    write: false,
    check: false,
    ...options,
  };
  const { target, writes } = desiredWrites(normalized);
  const changed = [];
  const conflicts = [];

  for (const file of writes) {
    const current = readIfExists(file.path);
    if (current === file.content) continue;
    const exists = Boolean(current);
    if (file.kind === "adr" && exists) {
      conflicts.push(path.relative(target, file.path));
      continue;
    }
    changed.push(path.relative(target, file.path));
    if (normalized.write && !normalized.check) {
      fs.mkdirSync(path.dirname(file.path), { recursive: true });
      fs.writeFileSync(file.path, file.content, "utf8");
    }
  }

  return {
    target,
    mode: normalized.check ? "check" : normalized.write ? "write" : "dry-run",
    writes: writes.map((file) => ({
      path: path.relative(target, file.path),
      kind: file.kind,
    })),
    changed,
    conflicts,
    ok: conflicts.length === 0 && (!normalized.check || changed.length === 0),
  };
}

function printText(result) {
  console.log(`decision capture ${result.mode}`);
  console.log(`target: ${result.target}`);
  if (result.writes.length === 0) console.log("writes: none");
  else {
    console.log("writes:");
    for (const write of result.writes) console.log(`  ${write.kind}: ${write.path}`);
  }
  if (result.changed.length > 0) console.log(`changed: ${result.changed.join(", ")}`);
  if (result.conflicts.length > 0) console.log(`conflicts: ${result.conflicts.join(", ")}`);
}

function main() {
  const args = parseArgs(process.argv);
  const result = run(args);
  if (args.json) process.stdout.write(`${JSON.stringify(result, null, 2)}\n`);
  else printText(result);
  if (!result.ok) process.exitCode = 1;
}

if (require.main === module) {
  try {
    main();
  } catch (error) {
    console.error(error.message);
    process.exit(1);
  }
}

module.exports = {
  GLOSSARY_MARKER_START,
  desiredWrites,
  formatAdr,
  run,
  slugify,
  upsertGlossary,
};
