#!/usr/bin/env node

'use strict';

const fs = require('fs');
const path = require('path');
const { loadSkill } = require('./parse-skill');

function renderOpenAIYaml(parsedSkill) {
  const displayName = (parsedSkill.frontmatter.name || 'unknown').replace(/"/g, '\\"');
  const shortDescription = (parsedSkill.frontmatter.description || '').replace(/"/g, '\\"');

  return `# Generated by Sinan. Do not edit manually.
interface:
  display_name: "${displayName}"
  short_description: "${shortDescription}"
policy:
  allow_implicit_invocation: true
`;
}

function ensureDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function projectSkillToCodex(sourceDir, targetBaseDir, skillName, options = {}) {
  const parsedSkill = loadSkill(sourceDir, skillName);
  if (parsedSkill.errors && parsedSkill.errors.length > 0) {
    throw new Error(`Skill "${skillName}" has validation errors: ${parsedSkill.errors.join(', ')}`);
  }
  const targetDir = path.join(targetBaseDir, skillName);
  const targetSkillPath = path.join(targetDir, 'SKILL.md');
  const targetYamlPath = path.join(targetDir, 'agents', 'openai.yaml');

  if (!options.dryRun) {
    ensureDir(path.dirname(targetSkillPath));
    fs.copyFileSync(parsedSkill.path, targetSkillPath);
    ensureDir(path.dirname(targetYamlPath));
    fs.writeFileSync(targetYamlPath, renderOpenAIYaml(parsedSkill), 'utf8');
  }

  return {
    skillName,
    parsedSkill,
    outputs: {
      skillPath: targetSkillPath,
      openaiYamlPath: targetYamlPath,
    },
  };
}

module.exports = Object.freeze({
  renderOpenAIYaml,
  projectSkillToCodex,
});
