#!/usr/bin/env node

'use strict';

const fs = require('fs');
const path = require('path');
const { loadAgent } = require('./parse-agent');

const MODEL_MAP = Object.freeze({
  opus: 'gpt-5.4',
  sonnet: 'gpt-5.4-mini',
  haiku: 'gpt-5.4-mini',
});

const EFFORT_MAP = Object.freeze({
  high: 'high',
  medium: 'medium',
  low: 'low',
});

function renderCodexToml(parsedAgent) {
  const model = MODEL_MAP[parsedAgent.frontmatter.model] || 'gpt-5.4';
  const effort = EFFORT_MAP[parsedAgent.frontmatter.effort] || 'high';
  const description = (parsedAgent.frontmatter.description || '').replace(/"/g, '\\"');
  const instructions = parsedAgent.body.length > 4000
    ? parsedAgent.body.slice(0, 4000) + '\n\n[Truncated by Sinan projection. See canonical agent definition for full instructions.]'
    : parsedAgent.body;

  return [
    '# Generated by Sinan. Do not edit manually.',
    `# Source: agents/${parsedAgent.frontmatter.name || parsedAgent.name}.md`,
    '',
    `name = "${parsedAgent.frontmatter.name || parsedAgent.name}"`,
    `description = "${description}"`,
    `model = "${model}"`,
    `model_reasoning_effort = "${effort}"`,
    '',
    'developer_instructions = """',
    instructions,
    '"""',
    '',
  ].join('\n');
}

function ensureDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function projectAgentToCodex(agentPath, targetBaseDir, options = {}) {
  const parsedAgent = loadAgent(agentPath);
  if (parsedAgent.errors && parsedAgent.errors.length > 0) {
    throw new Error(`Agent "${parsedAgent.name}" has validation errors: ${parsedAgent.errors.join(', ')}`);
  }
  const targetPath = path.join(targetBaseDir, `${parsedAgent.frontmatter.name || parsedAgent.name}.toml`);
  const toml = renderCodexToml(parsedAgent);

  if (!options.dryRun) {
    ensureDir(path.dirname(targetPath));
    fs.writeFileSync(targetPath, toml, 'utf8');
  }

  return {
    parsedAgent,
    output: {
      tomlPath: targetPath,
      toml,
    },
  };
}

module.exports = Object.freeze({
  renderCodexToml,
  projectAgentToCodex,
});
