#!/usr/bin/env node
"use strict";

const fs = require("node:fs");
const path = require("node:path");
const { extractWrite, runHook, safeCwd } = require("./hook-runtime");

// Sinan owns these agent-surface files. They must be created/updated by the
// packaged scaffold CLI (which writes via the filesystem, not the Write tool),
// so this guard never sees scaffold's own writes -- only agent hand-rolls.
function managedRelativePath(filePath, cwd) {
  if (!filePath) return "";
  const absolute = path.isAbsolute(filePath) ? filePath : path.join(cwd, filePath);
  const relative = path.relative(cwd, absolute).split(path.sep).join("/");
  return relative;
}

function isManagedSurface(relative) {
  if (!relative || relative.startsWith("../")) return false;
  if (relative === "AGENTS.md" || relative === "CLAUDE.md") return true;
  if (relative === ".agents" || relative.startsWith(".agents/")) return true;
  return false;
}

function hasSinanMarker(source) {
  if (!source) return false;
  const start = /^(?:<!-- |# )GENERATED BY SINAN: .+ v1 START(?: -->)?$/m.test(source);
  const end = /^(?:<!-- |# )GENERATED BY SINAN: .+ v1 END(?: -->)?$/m.test(source);
  return Boolean(start && end);
}

function readFileSafe(absolute) {
  try {
    return fs.readFileSync(absolute, "utf8");
  } catch {
    return null;
  }
}

function evaluateWrite(input = {}) {
  const { paths } = extractWrite(input);
  if (!paths.length) {
    return { decision: "allow", reason: "No write target found." };
  }
  const cwd = safeCwd(input.cwd || input.workspace || input.projectRoot);
  for (const candidate of paths) {
    const relative = managedRelativePath(candidate, cwd);
    if (!isManagedSurface(relative)) continue;
    const absolute = path.isAbsolute(candidate) ? candidate : path.join(cwd, candidate);
    const existing = readFileSafe(absolute);
    if (existing && hasSinanMarker(existing)) continue; // managed file: manual edits around blocks are fine
    return {
      decision: "block",
      path: relative,
      reason:
        `Sinan owns agent-surface files. Run \`sinan scaffold\` (or \`sinan scaffold --replace-entrypoints\` to repair ` +
        `bad entrypoints) instead of hand-writing ${relative}.`,
      rule: "managed-surface-write",
    };
  }
  return { decision: "allow", reason: "No managed agent-surface write detected." };
}

function writeGuard(input = {}) {
  const result = evaluateWrite(input);
  if (result.decision !== "block") return null;
  return {
    hookSpecificOutput: {
      hookEventName: "PreToolUse",
      permissionDecision: "deny",
      permissionDecisionReason: `${result.reason} Rule: ${result.rule}.`,
    },
  };
}

if (require.main === module) {
  runHook(writeGuard);
}

module.exports = {
  evaluateWrite,
  hasSinanMarker,
  isManagedSurface,
  managedRelativePath,
  writeGuard,
};
