#!/usr/bin/env node

'use strict';

const SINAN_EVENT_IDS = Object.freeze({
  SESSION_START: 'session_start',
  SETUP: 'setup',
  PRE_TOOL: 'pre_tool',
  POST_TOOL: 'post_tool',
  POST_TOOL_BATCH: 'post_tool_batch',
  POST_TOOL_FAILURE: 'post_tool_failure',
  USER_PROMPT: 'user_prompt',
  USER_PROMPT_SUBMIT: 'user_prompt_submit',
  USER_PROMPT_EXPANSION: 'user_prompt_expansion',
  STOP: 'stop',
  STOP_FAILURE: 'stop_failure',
  SESSION_END: 'session_end',
  PRE_COMPACT: 'pre_compact',
  POST_COMPACT: 'post_compact',
  SUBAGENT_START: 'subagent_start',
  SUBAGENT_STOP: 'subagent_stop',
  PERMISSION_REQUEST: 'permission_request',
  PERMISSION_DENIED: 'permission_denied',
  INSTRUCTIONS_LOADED: 'instructions_loaded',
  FILE_CHANGED: 'file_changed',
  CWD_CHANGED: 'cwd_changed',
  CONFIG_CHANGE: 'config_change',
  TEAMMATE_IDLE: 'teammate_idle',
  ELICITATION: 'elicitation',
  ELICITATION_RESULT: 'elicitation_result',
  NOTIFICATION: 'notification',
  TASK_CREATED: 'task_created',
  TASK_COMPLETED: 'task_completed',
  WORKTREE_CREATE: 'worktree_create',
  WORKTREE_REMOVE: 'worktree_remove',
});

const SINAN_EVENT_ORDER = Object.freeze([
  SINAN_EVENT_IDS.SESSION_START,
  SINAN_EVENT_IDS.SETUP,
  SINAN_EVENT_IDS.USER_PROMPT_SUBMIT,
  SINAN_EVENT_IDS.USER_PROMPT_EXPANSION,
  SINAN_EVENT_IDS.PRE_TOOL,
  SINAN_EVENT_IDS.POST_TOOL,
  SINAN_EVENT_IDS.POST_TOOL_BATCH,
  SINAN_EVENT_IDS.POST_TOOL_FAILURE,
  SINAN_EVENT_IDS.USER_PROMPT,
  SINAN_EVENT_IDS.STOP,
  SINAN_EVENT_IDS.STOP_FAILURE,
  SINAN_EVENT_IDS.SESSION_END,
  SINAN_EVENT_IDS.PRE_COMPACT,
  SINAN_EVENT_IDS.POST_COMPACT,
  SINAN_EVENT_IDS.SUBAGENT_START,
  SINAN_EVENT_IDS.SUBAGENT_STOP,
  SINAN_EVENT_IDS.TEAMMATE_IDLE,
  SINAN_EVENT_IDS.PERMISSION_REQUEST,
  SINAN_EVENT_IDS.PERMISSION_DENIED,
  SINAN_EVENT_IDS.INSTRUCTIONS_LOADED,
  SINAN_EVENT_IDS.FILE_CHANGED,
  SINAN_EVENT_IDS.CWD_CHANGED,
  SINAN_EVENT_IDS.CONFIG_CHANGE,
  SINAN_EVENT_IDS.ELICITATION,
  SINAN_EVENT_IDS.ELICITATION_RESULT,
  SINAN_EVENT_IDS.NOTIFICATION,
  SINAN_EVENT_IDS.TASK_CREATED,
  SINAN_EVENT_IDS.TASK_COMPLETED,
  SINAN_EVENT_IDS.WORKTREE_CREATE,
  SINAN_EVENT_IDS.WORKTREE_REMOVE,
]);

const REQUIRED_EVENT_FIELDS = Object.freeze([
  'event_id',
  'runtime',
  'timestamp',
]);

function isKnownSinanEvent(eventId) {
  return SINAN_EVENT_ORDER.includes(eventId);
}

module.exports = Object.freeze({
  SINAN_EVENT_IDS,
  SINAN_EVENT_ORDER,
  REQUIRED_EVENT_FIELDS,
  isKnownSinanEvent,
});
